In [1]:
import numpy as np


In [59]:
lfsr = {
    "degree": 6,
    "taps": [0, 5],
    "initial_state": np.array([1, 1, 1, 1, 1, 1]),
    "exp_period": 2**6 - 1,
    "states": set(),
    "output_bits": []
}

state = lfsr["initial_state"]

def new_bit(state, lfsr):
    # XOR all values in the tap positions that are 1
    tapped_values = state[lfsr["taps"]]
    print("Tapped values:", tapped_values)
    
    xor_result = np.bitwise_xor.reduce(tapped_values)
    
    print("XOR result:", xor_result)
    
    return xor_result

def shift(state, lfsr):
    state_str = np.array2string(state)
    lfsr["states"].add(state_str)
    bit = new_bit(state, lfsr)
    state[1:] = state[:-1]  # Shift all bits to the right
    state[0] = bit
    return state


def output_bits(state,lfsr):
    exp_period = lfsr["exp_period"]
    print("exp_period", exp_period)
    for i in range(exp_period):
        print("-------")
        output_bit = state[-1]
        
        lfsr["output_bits"].append(output_bit)

        print(state, "--->", output_bit)

        state = shift(state, lfsr)
        if np.array2string(state) in lfsr["states"]:
            print(f"Initial state repeated after {i} iterations")
            break

output_bits(state,lfsr) 
print(lfsr["output_bits"][:10])



exp_period 63
-------
[1 1 1 1 1 1] ---> 1
Tapped values: [1 1]
XOR result: 0
-------
[0 1 1 1 1 1] ---> 1
Tapped values: [0 1]
XOR result: 1
-------
[1 0 1 1 1 1] ---> 1
Tapped values: [1 1]
XOR result: 0
-------
[0 1 0 1 1 1] ---> 1
Tapped values: [0 1]
XOR result: 1
-------
[1 0 1 0 1 1] ---> 1
Tapped values: [1 1]
XOR result: 0
-------
[0 1 0 1 0 1] ---> 1
Tapped values: [0 1]
XOR result: 1
-------
[1 0 1 0 1 0] ---> 0
Tapped values: [1 0]
XOR result: 1
-------
[1 1 0 1 0 1] ---> 1
Tapped values: [1 1]
XOR result: 0
-------
[0 1 1 0 1 0] ---> 0
Tapped values: [0 0]
XOR result: 0
-------
[0 0 1 1 0 1] ---> 1
Tapped values: [0 1]
XOR result: 1
-------
[1 0 0 1 1 0] ---> 0
Tapped values: [1 0]
XOR result: 1
-------
[1 1 0 0 1 1] ---> 1
Tapped values: [1 1]
XOR result: 0
-------
[0 1 1 0 0 1] ---> 1
Tapped values: [0 1]
XOR result: 1
-------
[1 0 1 1 0 0] ---> 0
Tapped values: [1 0]
XOR result: 1
-------
[1 1 0 1 1 0] ---> 0
Tapped values: [1 0]
XOR result: 1
-------
[1 1 1 0 1 1] --->

In [46]:
lfsr = {
    "degree": 8,
    "taps": [0, 4, 5, 6],
    "exp_period": 2**8 - 1,
    "initial_state": np.array([0, 1, 0, 1, 0, 1, 0, 1]),
    "states": set(),
    "output_bits": []
    }

state = lfsr["initial_state"]

output_bits(state,lfsr)
print(lfsr["output_bits"][:20])

exp_period 255
repeated state 105
[1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0]


In [60]:
lfsr = {
    "degree": 10,
    "taps": [0, 2, 5, 9],
    "exp_period": 2**10 - 1,
    "initial_state": np.array([1, 1, 1, 0, 0, 0, 0, 1, 0, 1]),
    "states": set(),
    "output_bits": []
    }

state = lfsr["initial_state"]
output_bits(state,lfsr)
print("Output stream: ", ''.join(map(str, list(lfsr["output_bits"[:20]]))))

exp_period 1023
-------
[1 1 1 0 0 0 0 1 0 1] ---> 1
Tapped values: [1 1 0 1]
XOR result: 1
-------
[1 1 1 1 0 0 0 0 1 0] ---> 0
Tapped values: [1 1 0 0]
XOR result: 0
-------
[0 1 1 1 1 0 0 0 0 1] ---> 1
Tapped values: [0 1 0 1]
XOR result: 0
-------
[0 0 1 1 1 1 0 0 0 0] ---> 0
Tapped values: [0 1 1 0]
XOR result: 0
-------
[0 0 0 1 1 1 1 0 0 0] ---> 0
Tapped values: [0 0 1 0]
XOR result: 1
-------
[1 0 0 0 1 1 1 1 0 0] ---> 0
Tapped values: [1 0 1 0]
XOR result: 0
-------
[0 1 0 0 0 1 1 1 1 0] ---> 0
Tapped values: [0 0 1 0]
XOR result: 1
-------
[1 0 1 0 0 0 1 1 1 1] ---> 1
Tapped values: [1 1 0 1]
XOR result: 1
-------
[1 1 0 1 0 0 0 1 1 1] ---> 1
Tapped values: [1 0 0 1]
XOR result: 0
-------
[0 1 1 0 1 0 0 0 1 1] ---> 1
Tapped values: [0 1 0 1]
XOR result: 0
-------
[0 0 1 1 0 1 0 0 0 1] ---> 1
Tapped values: [0 1 1 1]
XOR result: 1
-------
[1 0 0 1 1 0 1 0 0 0] ---> 0
Tapped values: [1 0 0 0]
XOR result: 1
-------
[1 1 0 0 1 1 0 1 0 0] ---> 0
Tapped values: [1 0 1 0]
XOR result